In [112]:

from transformers import BertTokenizer, BertModel
import torch

c:\Users\giord\miniconda3\envs\weightedCL\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [113]:
from transformers import BertTokenizer, BertModel
import torch
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")
text = "red cat is meowing"
encoded_input = tokenizer(text, return_tensors='pt')
output1 = model(**encoded_input).last_hidden_state
text = "math lesson"
encoded_input = tokenizer(text, return_tensors='pt')
output2 = model(**encoded_input).last_hidden_state


In [114]:
output2[0].shape

torch.Size([4, 768])

In [115]:
output1 = torch.nn.functional.normalize(output1[0])
output2 = torch.nn.functional.normalize(output2[0])

In [116]:
(output1[0] @ output2[0].T)

C:\Users\giord\AppData\Local\Temp\ipykernel_2680\4171206031.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3701.)
  (output1[0] @ output2[0].T)


tensor(0.9294, grad_fn=<DotBackward0>)

In [69]:
!pip install sentence_transformers

  Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 11.0/11.0 MB 76.9 MB/s eta 0:00:00
Using cached scipy-1.13.1-cp39-cp39-win_amd64.whl (46.2 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [117]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('stsb-roberta-large')

c:\Users\giord\miniconda3\envs\weightedCL\lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\giord\.cache\huggingface\hub\models--sentence-transformers--stsb-roberta-large. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\giord\miniconda3\envs\weightedCL\lib\site-packages\transformers\tokenization_

In [131]:
text = "red cat is meowing"
embeddings1 = model.encode(['red cat is meowing', 'red dog is barking','a man picking out a vehicle from the trailer', 'a web animation of a businessman', 'a video showing footage from sporting events', 'three men talking about their youtube channel and thanking their viewers', 'advertisement of seat basket', 'a video of a young man in a white shirt inviting his colleagues to join him', 'some peole are sitting in hall', 'a group discusses a man s outfit', 'a man is singing on stage to a huge audience he is holding a microphone', 'all persons are wearing bikini dresses and playing in sea', 'few barbie dolls are playing one doll puts shoe to other barbie these are used to play by a kid', 'a man prepares some food in the kitchen', 'several women in pink outfits and various other styles are standing and smiling', 'a lady describes about workout and exercises for women', 'a compilation of vine videos is shown', 'a lady talks into a megaphone'] , convert_to_tensor=True)
text = ["red dog is barking", "red cat is meowing"]
embeddings2 = model.encode(text , convert_to_tensor=True)

In [132]:
embeddings1.shape

torch.Size([18, 1024])

In [133]:
embeddings1 = torch.nn.functional.normalize(embeddings1,dim=-1)
print(embeddings1.shape)
embeddings2 = torch.nn.functional.normalize(embeddings2,dim=-1)
embeddings1 @ embeddings2.T

torch.Size([18, 1024])


tensor([[ 3.8614e-01,  1.0000e+00],
        [ 1.0000e+00,  3.8614e-01],
        [-2.8847e-02, -1.0173e-01],
        [-2.5018e-02,  8.2522e-02],
        [-4.5637e-02, -1.5223e-01],
        [ 3.8316e-03,  2.3863e-01],
        [-1.6482e-02, -9.1886e-02],
        [ 4.9228e-03, -1.8898e-02],
        [ 1.6383e-01,  1.2463e-01],
        [ 8.1239e-02,  1.6601e-02],
        [-3.7230e-02,  1.5392e-01],
        [-8.0232e-02, -7.3004e-02],
        [ 7.4542e-02,  4.1487e-02],
        [ 6.0009e-02, -4.3059e-02],
        [ 1.1352e-01,  8.6773e-02],
        [ 1.3784e-01, -6.4094e-05],
        [ 5.3220e-02,  1.4555e-02],
        [ 2.1525e-01,  2.8739e-01]], device='cuda:0')

In [135]:
(embeddings1 @ embeddings2.T).shape

torch.Size([18, 2])

In [139]:
torch.softmax((embeddings2 @ embeddings1.T)/0.1, dim=-1)

tensor([[2.1498e-03, 9.9627e-01, 3.3896e-05, 3.5219e-05, 2.8657e-05, 4.6997e-05,
         3.8357e-05, 4.7513e-05, 2.3277e-04, 1.0192e-04, 3.1171e-05, 2.0276e-05,
         9.5315e-05, 8.2423e-05, 1.4074e-04, 1.7951e-04, 7.7013e-05, 3.8928e-04],
        [9.9563e-01, 2.1484e-03, 1.6344e-05, 1.0317e-04, 9.8635e-06, 4.9149e-04,
         1.8034e-05, 3.7418e-05, 1.5718e-04, 5.3364e-05, 2.1068e-04, 2.1782e-05,
         6.8443e-05, 2.9387e-05, 1.0765e-04, 4.5173e-05, 5.2283e-05, 8.0030e-04]],
       device='cuda:0')

In [137]:
torch.softmax((embeddings1 @ embeddings2.T)/0.1, dim=-1)

tensor([[0.0022, 0.9978],
        [0.9978, 0.0022],
        [0.6745, 0.3255],
        [0.2544, 0.7456],
        [0.7438, 0.2562],
        [0.0872, 0.9128],
        [0.6801, 0.3199],
        [0.5593, 0.4407],
        [0.5968, 0.4032],
        [0.6562, 0.3438],
        [0.1288, 0.8712],
        [0.4819, 0.5181],
        [0.5819, 0.4181],
        [0.7370, 0.2630],
        [0.5665, 0.4335],
        [0.7988, 0.2012],
        [0.5955, 0.4045],
        [0.3271, 0.6729]], device='cuda:0')

In [1]:
!pip install pillow

In [34]:
from PIL import Image
import os

def create_gif(image_folder, output_gif, duration=100):
    """
    Crea una GIF animata a partire da una cartella di immagini PNG.

    Args:
    - image_folder (str): La cartella che contiene le immagini PNG.
    - output_gif (str): Il percorso del file di output GIF.
    - duration (int): La durata di ogni frame in millisecondi (default: 100ms).
    """
    # Recupera tutte le immagini PNG dalla cartella specificata
    images = []
    def sort_files_by_modification_time(folder_path):
        # Get all files in the specified folder
        files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
    
        # Sort files based on modification time
        files.sort(key=lambda x: os.path.getmtime(x))
    
        return files
    
    for filename in sort_files_by_modification_time(image_folder):#os.listdir(image_folder):
        if filename.endswith(".png"):
            img_path = os.path.join(image_folder, filename)
            print(img_path)
            img = Image.open(img_path)
            images.append(img)
    
    # Verifica che ci siano immagini da combinare
    if not images:
        raise ValueError("Non sono state trovate immagini PNG nella cartella specificata.")

    # Salva le immagini come GIF animata
    images[0].save(
        output_gif,
        save_all=True,
        append_images=images[1:],  # Immagini da aggiungere alla GIF
        duration=duration,  # Durata di ogni frame
        loop=0  # Numero di loop (0 per loop infinito)
    )

    print(f"GIF animata creata: {output_gif}")




# Esempio di utilizzo
create_gif("C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA", "C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA/output.gif", duration=100)


C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 0.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 50.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 100.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 150.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 200.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 250.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 300.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 350.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 400.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLossCentroidsCTCVCA\latent space at 450.png
C:/Users/giord/Desktop/Projects/WeightCL/Prove/TrueLo

In [107]:
import torch
def compute_centroidsTest(text_embeddings, visual_embeddings, audio_embeddings):
    """
    Computes the centroid for each pair of samples between text embeddings and visual/audio embeddings
    by calculating the mean of the corresponding feature vectors across the two modalities.

    Parameters:
    - text_embeddings (torch.Tensor): Tensor of shape (batch_size1, feature_dim) representing text embeddings.
    - visual_audio_embeddings (torch.Tensor): Tensor of shape (batch_size2, feature_dim) representing visual/audio embeddings.

    Returns:
    - torch.Tensor: Tensor of shape (batch_size1, batch_size2, feature_dim) representing the centroid for each pair.
    """

    # Get batch sizes
    batch_size1 = text_embeddings.shape[0]   # For text embeddings
    batch_size2 = visual_embeddings.shape[0]  # For visual/audio embeddings

    # Compute centroids by averaging text and visual/audio embeddings
    # Expand the dimensions to allow pairwise computation
    text_expanded = text_embeddings.unsqueeze(1)  # Shape: [batch_size1, 1, feature_dim]
    print(text_expanded.shape)
    print(text_expanded)
    visual_expanded = visual_embeddings.unsqueeze(0)  # Shape: [1, batch_size2, feature_dim]
    print(visual_expanded.shape)
    print(visual_expanded)
    audio_expanded = audio_embeddings.unsqueeze(0)

    # Compute the centroid by averaging the embeddings
    
    centroids = (text_expanded + visual_expanded + audio_expanded) / 3.0
    #print(centroids)
    print(centroids)

    
    centroid_norms = torch.norm(centroids, dim=-1)

    #norm_condition = centroid_norms >= 0.5
    #centroid_norms = torch.where(norm_condition, centroid_norms, torch.tensor(0.0))

    return centroid_norms, centroids


In [108]:
a=torch.tensor([[0,1,1],[0,0,1]])
b=torch.tensor([[0,1,0],[1,0,1]])
c=torch.tensor([[0,0,1],[1,1,1]])

matrix_norm,centroids=compute_centroidsTest(a,b,c)
print(matrix_norm)
print(matrix_norm.T)

torch.Size([2, 1, 3])
tensor([[[0, 1, 1]],

        [[0, 0, 1]]])
torch.Size([1, 2, 3])
tensor([[[0, 1, 0],
         [1, 0, 1]]])
tensor([[[0.0000, 0.6667, 0.6667],
         [0.6667, 0.6667, 1.0000]],

        [[0.0000, 0.3333, 0.6667],
         [0.6667, 0.3333, 1.0000]]])
tensor([[0.9428, 1.3744],
        [0.7454, 1.2472]])
tensor([[0.9428, 0.7454],
        [1.3744, 1.2472]])


In [112]:
centroids.shape

torch.Size([2, 2, 3])

In [111]:
print(centroids[0]@centroids[0].T)

tensor([[0.8889, 1.1111],
        [1.1111, 1.8889]])


In [42]:
matrix_norm.sort(dim=-1,descending=True)

torch.return_types.sort(
values=tensor([[1.3744, 0.9428],
        [1.2472, 0.7454]]),
indices=tensor([[1, 0],
        [1, 0]]))

In [76]:
import torch.nn.functional as F

a = torch.tensor([1,-1,-1]).float()
target = torch.tensor([1,0,0]).float()
F.cross_entropy(a, target, label_smoothing=0.1)

tensor(0.3729)

In [15]:
import torch

# Create a sample matrix of shape [n, n]
n = 5
matrix = torch.randn(n, n)

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Remove the diagonal
# Create an index tensor for the rows and columns
mask = torch.ones((n, n), dtype=torch.bool)  # Create a boolean mask of shape [n, n]
mask.fill_diagonal_(False)                   # Set the diagonal to False

# Use the mask to index the original matrix
# Get only the non-diagonal elements
non_diag_elements = matrix[mask].view(n , n-1 )

# Print the new matrix
print("\nNew Matrix without Diagonal:")
print(non_diag_elements)


Original Matrix:
tensor([[-1.3026,  0.3969,  0.6831, -0.4572, -0.4039],
        [-0.4150, -0.9352,  0.1681, -0.1742, -1.1731],
        [ 1.3658, -0.4777,  0.2989, -0.8788, -1.5159],
        [ 0.1417,  0.8148,  1.0215, -0.2499,  0.9693],
        [ 0.7999, -0.2600,  0.1153, -1.0073, -0.8122]])

New Matrix without Diagonal:
tensor([[ 0.3969,  0.6831, -0.4572, -0.4039],
        [-0.4150,  0.1681, -0.1742, -1.1731],
        [ 1.3658, -0.4777, -0.8788, -1.5159],
        [ 0.1417,  0.8148,  1.0215,  0.9693],
        [ 0.7999, -0.2600,  0.1153, -1.0073]])


In [99]:
import numpy as np
def compute_similarity_matrix():
    # Define the number of items
    n_items = 10

    # Initialize an empty similarity matrix
    similarity_matrix = np.zeros((n_items, n_items))

    # Define the two groups
    group_1 = [0, 1, 2, 3, 4]  # Group 1 (0-4)
    group_2 = [5, 6, 7, 8, 9]  # Group 2 (5-9)

    # Fill the matrix with similarity values
    for i in range(n_items):
        for j in range(i, n_items):
            if i == j:
                similarity_matrix[i, j] = 1  # Perfect similarity with itself
            elif (i in group_1 and j in group_1) or (i in group_2 and j in group_2):
                similarity_matrix[i, j] = 0.8  # High similarity within the same group
            else:
                similarity_matrix[i, j] = 0  # Low similarity between groups

            similarity_matrix[j, i] = similarity_matrix[i, j]  # Ensure symmetry

    # Convert to torch tensor and move to GPU
    similarity_matrix = torch.tensor(similarity_matrix).to('cuda')

    # Print the raw similarity matrix
    print("Raw Similarity Matrix:")
    print(similarity_matrix)

    # If smoothing with sigmoid style
    #similarity_matrix = 1 - (1 / (1 + torch.exp(-5 * (similarity_matrix))))  # Smoothing to get values between 0 and 1
    #similarity_matrix = (1 / (1 + torch.exp(-5 * (similarity_matrix))))
    print("Smoothing Applied (Sigmoid Style):")
    print(similarity_matrix)

    # If linear decaying (if needed, you can uncomment this line)
    # similarity_matrix = 1 - similarity_matrix

    return similarity_matrix

In [100]:
similarity_matrix = compute_similarity_matrix()

Raw Similarity Matrix:
tensor([[1.0000, 0.8000, 0.8000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 1.0000, 0.8000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 1.0000, 0.8000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 0.8000, 1.0000, 0.8000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.8000, 0.8000, 0.8000, 0.8000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.8000, 0.8000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 1.0000, 0.8000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 1.0000, 0.8000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 0.8000, 1.0000,
         0.8000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.8000, 0.8000, 0.8000, 0.8000,
     

In [101]:
import torch.nn.functional as F

F.softmax(similarity_matrix,dim=0)

tensor([[0.1636, 0.1339, 0.1339, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1636, 0.1339, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1636, 0.1339, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1339, 0.1636, 0.1339, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.1339, 0.1339, 0.1339, 0.1339, 0.1636, 0.0602, 0.0602, 0.0602, 0.0602,
         0.0602],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1636, 0.1339, 0.1339, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1636, 0.1339, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1636, 0.1339,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1339, 0.1636,
         0.1339],
        [0.0602, 0.0602, 0.0602, 0.0602, 0.0602, 0.1339, 0.1339, 0.1339, 0.1339,
         0.1636]], device='c

In [102]:
similarity_matrix = similarity_matrix / 0.1
F.softmax(similarity_matrix,dim=0)

tensor([[6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 6.4869e-01, 8.7791e-02, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 8.7791e-02, 6.4869e-01, 8.7791e-02, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02, 6.4869e-01, 2.9450e-05,
         2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05],
        [2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 6.4869e-01,
         8.7791e-02, 8.7791e-02, 8.7791e-02, 8.7791e-02],
        [2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 2.9450e-05, 8.7791e-02,
         6.4869e-01, 8.7791e-02, 8.7791e-02, 8.7791e-02],
        [2.9450e-05, 2.9450

In [60]:
def extract_diagonal_elements(tensor):
    """
    Extract the elements [i, i, :] for each i from a tensor of shape [bs1, bs2, 512].
    
    Args:
    - tensor: A 3D tensor of shape (bs1, bs2, 512)
    
    Returns:
    - diagonal_elements: A 2D tensor of shape (min(bs1, bs2), 512)
    """
    bs1, bs2, feature_dim = tensor.shape
    min_bs = min(bs1, bs2)
    indices = torch.arange(min_bs)
    diagonal_elements = tensor[indices, indices]
    
    return diagonal_elements

def compute_centroids_angle(text_embeddings, visual_embeddings, audio_embeddings, norm_threshold=0.0):


    # Get batch sizes
    batch_size1 = text_embeddings.shape[0]   # For text embeddings
    batch_size2 = visual_embeddings.shape[0]  # For visual/audio embeddings

    # Compute centroids by averaging text and visual/audio embeddings
    # Expand the dimensions to allow pairwise computation
    text_expanded = text_embeddings.unsqueeze(1)  # Shape: [batch_size1, 1, feature_dim]
    visual_expanded = visual_embeddings.unsqueeze(0)  # Shape: [1, batch_size2, feature_dim]
    audio_expanded = audio_embeddings.unsqueeze(0)  # Shape: [1, batch_size2, feature_dim]

    # Compute the centroid by averaging the embeddings
    centroids = (text_expanded + visual_expanded + audio_expanded) / 3.0
    
    # Normalize the centroid vectors
    centroids = torch.nn.functional.normalize(centroids, dim=-1)
    print(centroids)
    diag_elements = extract_diagonal_elements(centroids)
    diag_elements_expanded = diag_elements.unsqueeze(1).expand_as(centroids)
    
    # Compute the cosine similarity using the dot product
    cosine_sim = torch.sum(centroids * diag_elements_expanded, dim=2)
    
    
    return cosine_sim

In [65]:
import torch

a = torch.tensor([[1,1,1]])
b = torch.tensor([[1,0,1],[1,0,1]])
c = torch.tensor([[1,1,1],[1,0,1]])

angles = compute_centroids_angle(a,b,c)
angles

tensor([[[0.6396, 0.4264, 0.6396],
         [0.6882, 0.2294, 0.6882]]])


tensor([[1.0000, 0.9782]])

In [62]:
angles.shape

torch.Size([2, 1])

In [73]:
def lalign(x, y, alpha=2):
    return (x - y).norm(dim=1).pow(alpha).mean()

x = torch.tensor([[0,1,1],[1,1,1]]).float()
y = torch.tensor([[0,0,0],[0,0,0]]).float()

lalign(x,y)

tensor(2.5000)

In [74]:
x-y

tensor([[0., 1., 1.],
        [1., 1., 1.]])

In [75]:
(x - y).norm(dim=1)

tensor([1.4142, 1.7321])

In [76]:
x.norm()

tensor(2.2361)

In [77]:

def compute_mean_angular_value_of_a_modality(cos_sim):
    #norm_modality = torch.norm(feat_modality,dim=1)
    #norm_modality = norm_modality.unsqueeze(1)
    #feat_modality = feat_modality/norm_modality

    #FEATURES SHOULD BE NORMALIZED
    

    #cos_sim = feat_modality@feat_modality.T
    #EXCLUDE THE DIAGONAL THAT IS 1 and make a matrix n-1xn-1
    # Initialize an empty list to hold the result
    result = []
    n=cos_sim.size(0)
    # Loop through the rows and columns, excluding the diagonal
    for i in range(n):
        row = []
        for j in range(n):
            if i != j:  # Exclude diagonal element
                row.append(cos_sim[i, j])
        result.append(row)
    # Convert the result list to a tensor
    cos_sim_no_diag = torch.tensor(result)

    return cos_sim_no_diag


In [84]:
a = torch.randn(16).reshape(4,4).float()
a


tensor([[ 0.9480,  0.7107,  0.4440,  0.5410],
        [ 0.0288,  0.5852,  1.4908, -1.4082],
        [ 0.2320, -1.0609, -0.1234,  0.4018],
        [-0.9940, -1.1637,  0.4729, -0.7456]])

In [85]:
b = compute_mean_angular_value_of_a_modality(a)

In [86]:
b

tensor([[ 0.7107,  0.4440,  0.5410],
        [ 0.0288,  1.4908, -1.4082],
        [ 0.2320, -1.0609,  0.4018],
        [-0.9940, -1.1637,  0.4729]])

In [87]:
b.mean()

tensor(-0.0254)

In [88]:
a.mean()

tensor(0.0225)

In [100]:
import torch

def uniformity(features_modality1, features_modality2):
    """
    Calculate the uniformity metric for two modalities based on their features.

    Args:
        features_modality1 (torch.Tensor): Feature matrix of modality 1 with shape [bs, d].
        features_modality2 (torch.Tensor): Feature matrix of modality 2 with shape [bs, d].

    Returns:
        float: Uniformity metric (-W2).
    """
    # Concatenate the features of the two modalities
    Z = torch.cat([features_modality1, features_modality2], dim=0)  # Shape: [2 * bs, d]

    # Compute the sample mean \mu_hat and covariance \Sigma
    mu_hat = torch.mean(Z, dim=0)  # Shape: [d]
    Sigma = torch.cov(Z.T)  # Shape: [d, d]

    # Calculate the trace and square root of the covariance matrix
    trace_Sigma = torch.trace(Sigma)  # Scalar
    sqrt_Sigma = torch.linalg.matrix_power(Sigma, 1 // 2)  # Matrix square root of Sigma, shape: [d, d]
    trace_sqrt_Sigma = torch.trace(sqrt_Sigma)  # Scalar

    # Dimensionality of the features
    m = Z.shape[1]

    # Compute the quadratic Wasserstein distance W2
    W2 = torch.sqrt(
        torch.norm(mu_hat)**2 + 1 + trace_Sigma - (2 / torch.sqrt(torch.tensor(m, dtype=Sigma.dtype))) * trace_sqrt_Sigma
    )

    # Return the uniformity metric (-W2)
    return -W2.item()

# Example usage

# Generate some random data for testing
bs, d = 64, 512
features_modality1 = torch.randn(bs, d)
features_modality2 = torch.randn(bs, d)

# Compute uniformity metric
uniformity_metric = uniformity(features_modality1, features_modality2)
print(f"Uniformity Metric: {uniformity_metric}")

Uniformity Metric: -21.68321990966797


In [95]:
import torch

a = torch.arange(1, 10).reshape(3, 3).float()

In [99]:
a.shape

torch.Size([3, 3])

In [97]:
a.diag()

tensor([1., 5., 9.])

In [98]:
a.diag().mean()

tensor(5.)

In [146]:
def calc_wasserstein_distance(x):
    N = x.size(0)
    dim = x.size(1)

    x_center = torch.mean(x, dim=0, keepdim=True)
    covariance = torch.mm((x-x_center).t(), x-x_center)/N

    mean =  x.mean(0)
    np_mean = mean.data.cpu().numpy()
    np_covariance = covariance.data.cpu().numpy()
   
    ##calculation of part1
    part1 = np.sum(np.multiply(np_mean, np_mean))

    ##calculation of part2
    eps = 1e-8 
    S, Q = np.linalg.eig(np_covariance)
    S = S + eps
    print(S)
    mS = np.sqrt(np.diag(S))
    covariance_2 = np.dot(np.dot(Q, mS), Q.T)

    part2 = np.trace(np_covariance - 2.0/np.sqrt(dim) * covariance_2)
    wasserstein_distance = math.sqrt(part1 + 1 + part2)
    return -wasserstein_distance 

In [147]:

import numpy as np
import math 

bs, d = 64, 512
features_modality1 = torch.randn(bs, d)
features_modality2 = torch.randn(bs, d)
Z = torch.cat([features_modality1, features_modality2], dim=0) 

calc_wasserstein_distance(Z)

[ 9.08640766e+00+0.00000000e+00j  8.85001469e+00+0.00000000e+00j
  8.63491631e+00+0.00000000e+00j  8.44807911e+00+0.00000000e+00j
  8.20698261e+00+0.00000000e+00j  7.90522242e+00+0.00000000e+00j
  7.88740826e+00+0.00000000e+00j  7.72908497e+00+0.00000000e+00j
  7.57684708e+00+0.00000000e+00j  7.48633623e+00+0.00000000e+00j
  7.44882154e+00+0.00000000e+00j  7.15277576e+00+0.00000000e+00j
  7.10605097e+00+0.00000000e+00j  7.03209734e+00+0.00000000e+00j
  6.90346909e+00+0.00000000e+00j  6.81581163e+00+0.00000000e+00j
  6.69732618e+00+0.00000000e+00j  6.62449408e+00+0.00000000e+00j
  6.54616880e+00+0.00000000e+00j  6.50844765e+00+0.00000000e+00j
  6.39214516e+00+0.00000000e+00j  6.24675179e+00+0.00000000e+00j
  6.15360451e+00+0.00000000e+00j  6.08941746e+00+0.00000000e+00j
  5.97221041e+00+0.00000000e+00j  5.93961287e+00+0.00000000e+00j
  5.84548950e+00+0.00000000e+00j  5.79978228e+00+0.00000000e+00j
  5.74395227e+00+0.00000000e+00j  5.64841318e+00+0.00000000e+00j
  5.55612803e+00+0.000000

C:\Users\giord\AppData\Local\Temp\ipykernel_2680\701303171.py:24: ComplexWarning: Casting complex values to real discards the imaginary part
  wasserstein_distance = math.sqrt(part1 + 1 + part2)


-22.22273626395251

In [142]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]).float()
print(a.shape)
torch.mean(a, dim=-1, keepdim=True)


torch.Size([3, 3])


tensor([[2.],
        [5.],
        [8.]])